fieldLayouts:
  2db5a02c-4dc7-4f3a-b00f-c2dbb8387a09:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9e13b4a1-6657-410b-b0bf-2f1c79aed349
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: 'Number of Players'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: ea5b6112-8006-41df-a493-90b2ddf9bb35
            instructions: ''
            label: Minimum
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9fca3e04-34c4-4237-868a-4bcd6af77ab0
            instructions: ''
            label: Maximum
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0f92cf2e-a506-47e6-9e37-145e84a7a329
            instructions: ''
            label: Best
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: Duration
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 90bb7b2a-a4c5-42c7-9cc0-530e7ace785a
            instructions: ''
            label: Minimum
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9a797faf-0220-4772-90a2-5878d5e2ede0
            instructions: ''
            label: Maximum
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
handle: boardGames
hasTitleField: true
name: 'Board Games'
section: 34aadfc4-3004-4129-aaa3-84bfb5930eac
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
