contentColumnType: smallint(2)
fieldGroup: 740c9134-cf27-436b-bb01-f1c640819c02
handle: maxNumPlayers
instructions: ''
name: 'Maximum number of players'
searchable: false
settings:
  decimals: 0
  defaultValue: '4'
  max: '10'
  min: '2'
  prefix: ''
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
