dateModified: 1602105954
email:
  fromEmail: hello@eaglepeakweb.com
  fromName: 'Board Games'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
system:
  edition: solo
  live: true
  name: 'Board Games'
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
